# Generated by Django 2.0 on 2018-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='avatar\\default.jpg', upload_to='user/%Y%m', verbose_name='头像'),
        ),
    ]
