# Generated by Django 2.0 on 2018-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181125_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='avatar\\default.png', upload_to='user/%Y%m', verbose_name='头像'),
        ),
    ]
