# Generated by Django 2.0 on 2018-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SowingMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='轮播图标题')),
                ('images', models.ImageField(default='sowingmap/default.jpg', upload_to='sowin/%Y%m', verbose_name='轮播图')),
                ('index_images', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
