# Generated by Django 2.0 on 2018-11-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0003_auto_20181122_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_number', models.IntegerField(default=0)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforum.Forum', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子阅读数',
                'verbose_name_plural': '帖子阅读数',
            },
        ),
    ]
