# Generated by Django 2.0 on 2018-11-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0004_forumread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumread',
            name='read_number',
            field=models.IntegerField(verbose_name='阅读数量'),
        ),
    ]
