# Generated by Django 2.0 on 2018-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0005_auto_20181124_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumread',
            name='read_number',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
