# Generated by Django 2.0 on 2018-11-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0006_auto_20181124_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='read_number',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
